#Week5 Tests Assingment#

####Question 1:####
#Does the mean beef preference score differs among gender of participants?
#Hypothesis1: The mean beef preference score (likert scale, categorical) is different among gender of participants
##Null_Hypothesis: The mean beef preference score (likert scale, categorical) is not different among gender of participants

#1.Input data into R####
#setting directory and reading data
setwd("C:/Users/lili-/OneDrive/Área de Trabalho/biol5504_rproject_gomes/lisleypgomes")
amazon_data=read.csv("BIOL5504_gomes_dataset.csv", header = TRUE,sep = ";") 

#2.Permutation test Hypothesis1####
#use jar example to illustrate sampling procedure

for (i in 1:10000) {
  colonyboot <- sample(c(field,forest)) ## colonyboot is a object of the scrambled (random). scramble if you don't set a number, it sample the number of observations you will have (N)
  ## pick out forest & field samples
  forestboot <- colonyboot[1:length(forest)] #this says assign the first six colonies to forest. For the first several lopps of colonyboot, call them forestboot
  fieldboot <- colonyboot[(length(forest)+1):length(colonyboot)] #call all the rest of the observations as field. the lenght of total observations in the colony boot factor + 1. assign the rest of the colonies to field
  
  #if you had a dataframe it would look like #So most of us would be working with dataframes, not vectros, we have to call out specifi collumns, different than what has been done up here.
  #forestboot <- colonyboot[1:length(ants$place[ants$place=="forest"])] #this says assign the first six colonies to forest
  #fieldboot <- colonyboot[(length(ants$place[ants$place=="forest"])+1):length(ants$place)] #this says assign the rest of the observations to field
  
  ## compute & store difference in means
  res[i] <- mean(fieldboot)-mean(forestboot) # take the mean of my field data, the arbitrary scrumbled field data, and subtract the mena of the arbritary forest and store that in a place called res #calculate the difference in the field means and the forest means
  #[i] says "where i", and i is a counter, after running this loop, i should be 1000
}

#what is our observed mean difference?
obs <- mean(field)-mean(forest)
obs

#if you have a dataframe
#obs <- mean(ants$field[ants$place=="field"])-mean(ants$forest[ants$place=="forest"])


hist(res,col="gray",las=1,main="") #makes a histagram of the results as the null distribution
abline(v=obs,col="red") #compares the null distribution with our actual result (the red line). that means we are seeing a very extreme effect as if it was generated by chance (gray histogram), so it is not null. We can use these values to get the P value

##so how do we get our p-value?
res[res>=obs] #give me all values of res where res is equal or greater than our observed value
length(res[res>=obs])
240/10000 #change the number to match the result of res and divide by the number of iterations
mean(res>=obs)     #here you calculate the p value (as you did in the last two rows above)   
#using mean(permutations>=obs)) is a trick to calculate the proportion: 
#the logical statement returns a logical (FALSE/TRUE) vector, which then gets converted to a 0/1 vector when you ask R to take the mean, 
#so this is equivalent to counting the number of true values and dividing by the length

#FINDINGs 1



#3. Classic test Hypothesis1####


#FINDINGs 1


####Question 2:####
#Does the mean age of participants differ among previous residence (rural vs. urban) of participants?
#Hypothesis1: The mean age of participants is different among previous residence (rural vs. urban) of participants
##Null_Hypothesis: The mean age of participants is not different among previous residence (rural vs. urban) of participants

#4.Permutation test Hypothesis2####


#FINDINGs 2


#5.Permutation test Hypothesis2####


#FINDINGs 2

